name = "poisson_binomial_comparison"
version = "0.1.0"
defaultTargets = ["PoissonBinomialComparison", "poisson_binomial_comparison"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "5ed2965256430c3649e86755f9576b54eca72435"

[[lean_lib]]
name = "PoissonBinomialComparison"

[[lean_exe]]
name = "poisson_binomial_comparison"
root = "Main"
